# fly.toml app configuration file generated for predial-alcaldias on 2024-08-05T21:04:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'predial-alcaldias'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
